apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx-server
    image: nginx
    ports:
    - containerPort: 8081
  - name : webwatcher
    image: afakharany/watcher:latest
  